version: '2'
services:
  zookeeper:
    image: zookeeper:3.4.9
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CONNECTION_TIMEOUT_MS: "60000"
  kafka:
    image: wurstmeister/kafka:0.10.1.1
    ports:
      - 9092:9092
      - 7203:7203
    environment:
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: "60000"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS: "60000"
      KAFKA_ZOOKEEPER_SYNC_TIME_MS: "60000"
      KAFKA_ADVERTISED_HOST_NAME: "<your ip here>"
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
  master:
    image: singularities/spark:2.0
    command: start-spark master
    hostname: master
    volumes:
      - ./src:/src
    environment:
      HDFS_USER: root
    depends_on:
      - kafka 
  worker:
    image: singularities/spark:2.0
    command: start-spark worker master
    environment:
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 2g
      HDFS_USER: root
    links:
      - master
    volumes:
      - ./src:/src
    depends_on:
      - master
  cassandra-seed:
    container_name: cassandra-seed-node
    image: cassandra:3.11.0
    ports:
      - "9042:9042"   # Native transport
      - "7199:7199"   # JMX
      - "9160:9160"   # Thrift clients
    volumes:
      - ./src:/src

  cassandra-node-1:
    image: cassandra:3.11.0
    command: /bin/bash -c "echo 'Waiting for seed node' && sleep 30 && /docker-entrypoint.sh cassandra -f"
    environment:
      - "CASSANDRA_SEEDS=cassandra-seed-node"
    depends_on:
      - "cassandra-seed"
  # you cannot have multiple nodes join the cluster at the same time when
  # cassandra.consistent.rangemovement is true so we further delay it to give it time to stabilize
  cassandra-node-2:
    image: cassandra:3.11.0
    command: /bin/bash -c "echo 'Waiting for seed node' && sleep 80 && /docker-entrypoint.sh cassandra -f"
    environment:
      - "CASSANDRA_SEEDS=cassandra-seed-node"
    depends_on:
      - "cassandra-seed"
